
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ChakraProvider } from '@chakra-ui/react'
import {Providers} from "@/app/providers";
import React from "react";
import {QueryClient, QueryClientProvider} from "@tanstack/react-query";
import type { AppProps } from "next/app";


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
// Create a client
const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {



  return (
        <html lang="en">
        <body className={inter.className}>
        <QueryClientProvider client={queryClient}>
             <Providers>
                  {children}
              </Providers>
        </QueryClientProvider>
        </body>
        </html>

  )
}
